name: CI-dev-pipeline
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    env:
      AWS_ACCESS_KEY_ID: myawskey
      AWS_SECRET_ACCESS_KEY: myawssecret
      S3_PATH: s3://my-bucket/backup
      S3_ENDPOINT: http://s3:9000
      AES_PASSPHRASE: secret
      AWS_DEFAULT_OUTPUT: json
      AWS_DEFAULT_REGION: us-east-1
      EXCLUDE_FILES: ./file_that_should_be_excluded
    steps:
      - uses: actions/checkout@v2

      - name: Run backup
        run: ./test/test_backup.sh

      - name: Run restore
        run: ./test/test_restore.sh

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            README.md

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: richardwiden/docker-backup-to-s3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: richardwiden/docker-backup-to-s3
          readme-filepath: ./README.md
