name: CI-dev-pipeline
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ] # to change to develop
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "docker-backup-to-s3"
      - name: RunOne
        run: |
          echo Hello, world!
      - name: Build docker
        run: |
          echo ---Building and starting up docker---
          docker kill s3 || true
          docker network rm local|| true
          docker network create local

          docker build --tag docker-backup-to-s3:latest  docker-backup-to-s3
          docker run -d  --rm --name s3     --network local -p 9000:9000  altmannmarcelo/minio:latest
          docker run  --rm  --name backup --network local  docker-backup-to-s3:latest  \
            -e AWS_DEFAULT_REGION=eu-central-1 \
          	-e AWS_ACCESS_KEY_ID=myawskey \
          	-e AWS_SECRET_ACCESS_KEY=myawssecret \
          	-e S3_PATH=s3://my-bucket/backup/ \
            -e S3_ENDPOINT=http://s3 \
          	-e AES_PASSPHRASE=secret \
          	-e CRON_SCHEDULE='0 12 * * *' \
          	-v /home/user/data:/data:ro \
             richardwiden/docker-backup-to-s3:latest backup-once

          docker ps
          echo ---Containers up---
          docker kill s3 || true
          docker kill pg ||true
          docker network rm local || true