name: CI-dev-pipeline
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] # to change to develop
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    env:
      AWS_ACCESS_KEY_ID: myawskey
      AWS_SECRET_ACCESS_KEY: myawssecret
      S3_PATH: s3://my-bucket/backup
      S3_ENDPOINT: http://s3:9000
      AES_PASSPHRASE: secret
      AWS_EC2_METADATA_DISABLED: true #https://github.com/aws/aws-cli/issues/5262#issuecomment-705832151
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Run backup
        run: ./test/test_backup.sh

      - name: Run restore
        run: ./test/test_restore.sh

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            start.sh
            backup.sh
            restore.sh
            s3cfg
            Dockerfile
            LICENSE
            README.md